# =============================================================================
# Development Docker Compose Override
# =============================================================================

version: '3.8'

services:
  libgen-bot-dev:
    # Development optimizations
    environment:
      - LOG_LEVEL=DEBUG
      - LIBGEN_MAX_RESULTS=10
      - BOT_BOOKS_PER_PAGE=2
      - LIBGEN_SEARCH_TIMEOUT=30
      - BOT_DOWNLOAD_LINKS_TIMEOUT=15
      - BOT_CANCELLATION_CHECK_INTERVAL=0.1
      - BOT_CANCELLATION_CHECKS_COUNT=20
    
    # Volume mounts for hot reload
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
      # Exclude node_modules and other build artifacts
      - /app/__pycache__
      - /app/.pytest_cache
      - /app/.coverage
    
    # Development restart policy
    restart: unless-stopped
    
    # Override command for development
    command: ["python", "main.py"]
    
    # Port exposure for debugging
    ports:
      - "8000:8000"
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
